import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./Home/components/header";
import { Footer } from "./Home/components/footer";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`inter.className min-h-screen  items-center p-7  space-y-5`}
      >
        <Header />

        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
