import { Footer } from "./components/footer";
import { Header } from "./components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen items-center p-7 space-y-5">
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
